# Generated by Django 6.0 on 2026-01-05 23:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chambre', models.CharField(max_length=10, unique=True)),
                ('type_chambre', models.CharField(choices=[('SIMPLE', 'Simple'), ('DOUBLE', 'Double'), ('SUITE', 'Suite'), ('DELUXE', 'Deluxe')], max_length=20)),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('nombre_lits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie en m²', max_digits=5)),
                ('etage', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPEE', 'Occupée'), ('MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20)),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['numero_chambre'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Guinée', max_length=100)),
                ('piece_identite', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire')], max_length=20)),
                ('numero_piece', models.CharField(max_length=50, unique=True)),
                ('date_naissance', models.DateField()),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Supplémentaire',
                'verbose_name_plural': 'Services Supplémentaires',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_debut_sejour', models.DateField()),
                ('date_fin_sejour', models.DateField()),
                ('nombre_adultes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('nombre_enfants', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('nombre_nuits', models.IntegerField(editable=False)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.client')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations_gerees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee_effective', models.DateTimeField()),
                ('date_depart_effective', models.DateTimeField(blank=True, null=True)),
                ('date_checkin', models.DateTimeField(auto_now_add=True)),
                ('date_checkout', models.DateTimeField(blank=True, null=True)),
                ('nombre_personnes', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestion.reservation')),
            ],
            options={
                'verbose_name': 'Séjour',
                'verbose_name_plural': 'Séjours',
                'ordering': ['-date_checkin'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('VIREMENT', 'Virement'), ('MOBILE_MONEY', 'Mobile Money')], max_length=30)),
                ('reference_transaction', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=20)),
                ('sejour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.sejour')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='ReservationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.reservation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.servicesupplementaire')),
            ],
            options={
                'verbose_name': 'Service de Réservation',
                'verbose_name_plural': 'Services de Réservation',
                'unique_together': {('reservation', 'service')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='services_supplementaires',
            field=models.ManyToManyField(related_name='reservations', through='gestion.ReservationService', to='gestion.servicesupplementaire'),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('RECEPTIONNISTE', 'Réceptionniste')], max_length=20)),
                ('statut_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
    ]
